services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    network_mode: service:netbird
    depends_on:
      netbird:
        condition: service_started
    restart: unless-stopped
    init: true
    volumes:
      - /srv/docker/data/owntracks/mosquitto/config:/mosquitto/config:Z
      - /srv/docker/data/owntracks/mosquitto/data:/mosquitto/data:Z
      - /srv/docker/data/owntracks/mosquitto/log:/mosquitto/log:Z
    labels:
      glance.name: MQTT
      glance.parent: owntracks

  frontend:
    image: owntracks/frontend
    container_name: owntracks-frontend
    network_mode: service:netbird
    depends_on:
      netbird:
        condition: service_started
    restart: unless-stopped
    init: true
    environment:
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=8083
    labels:
      glance.name: OwnTracks
      glance.icon: /assets/owntracks.png
      glance.url: https://tracks.server.netbird.cloud
      glance.description: Location Sharing
      glance.id: owntracks
      glance.category: user-facing

  recorder:
    image: owntracks/recorder:latest
    container_name: owntracks-recorder
    network_mode: service:netbird
    depends_on:
      netbird:
        condition: service_started
      mqtt:
        condition: service_started
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      - OTR_HOST=127.0.0.1
      - OTR_PORT=1883
      - OTR_TOPIC=owntracks/#
      - TZ=UTC
    volumes:
      - /srv/docker/data/owntracks/recorder/config:/config:Z
      - /srv/docker/data/owntracks/recorder/store:/store:Z
    labels:
      glance.name: Recorder
      glance.parent: owntracks

  netbird:
    image: netbirdio/netbird:latest
    container_name: owntracks-nb
    hostname: tracks
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_RAW
    cap_drop:
      - ALL
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run
    environment:
      - NB_SETUP_KEY=${NB_SETUP_KEY}
      - NB_ENABLE_ROSENPASS=true
    volumes:
      - netbird-state:/var/lib/netbird:z
    ports:
      - "127.0.0.1:8085:80"
      - "127.0.0.1:1883:1883"
    deploy:
      resources:
        limits:
          memory: 128M
    labels:
      glance.parent: owntracks
      glance.name: NetBird

volumes:
  netbird-state:
