services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    restart: unless-stopped
    ports:
      - "127.0.0.1:8443:8443"
      - "25500-25600:25500-25600"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /srv/docker/data/crafty/backups:/crafty/backups:Z
      - /srv/docker/data/crafty/logs:/crafty/logs:Z
      - /srv/docker/data/crafty/servers:/crafty/servers:Z
      - /srv/docker/data/crafty/config:/crafty/app/config:Z
      - /srv/docker/data/crafty/import:/crafty/import:Z
    labels:
      glance.name: Crafty Controller
      glance.icon: /assets/crafty.png
      glance.url: https://crafty.server.netbird.cloud
      glance.description: Minecraft Server Manager
      glance.id: crafty
