services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    network_mode: service:tailscale
    security_opt:
      - label:disable # Prevent issues with SELinux
    volumes:
      - /srv/docker/data/glance/config:/app/config:ro,Z
      - /srv/docker/data/glance/assets:/app/assets:ro,Z
      - /etc/timezone:/etc/timezone:ro,Z
      - /etc/localtime:/etc/localtime:ro,Z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    labels:
      glance.name: Glance
      glance.icon: dashboard
      glance.url: http://home:8080
      glance.description: Dashboard with feeds
      glance.id: glance

  tailscale:
    image: dhi.io/tailscale:1
    container_name: glance-ts
    restart: unless-stopped
    command:
      - /usr/local/bin/containerboot
    env_file:
      - .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true
      - TS_SERVE_CONFIG=/config/serve.json
    hostname: home
    cap_add:
      - NET_ADMIN
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run
    volumes:
      - tailscale_state:/var/lib/tailscale:z
      - ./serve.json:/config/serve.json:ro,Z
    devices:
      - /dev/net/tun:/dev/net/tun
    deploy:
      resources:
        limits:
          memory: 128M
    labels:
      glance.parent: glance
      glance.name: Tailscale

volumes:
  tailscale_state:
