services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    security_opt:
      - label:disable 
    ports:
      - "127.0.0.1:8082:8080"
    volumes:
      - /srv/docker/data/glance/config:/app/config:ro,Z
      - /srv/docker/data/glance/assets:/app/assets:ro,Z
      - /etc/timezone:/etc/timezone:ro,Z
      - /etc/localtime:/etc/localtime:ro,Z
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    labels:
      glance.name: Glance
      glance.icon: /assets/glance.png
      glance.url: http://localhost:8082
      glance.description: This Dashboard
      glance.id: glance
