services:
  server:
    image: actualbudget/actual-server:latest
    container_name: actual_server
    restart: unless-stopped
    ports:
      - "127.0.0.1:5006:5006"
    volumes:
      - /srv/docker/data/actual_budget/actual-data:/data:Z
    labels:
      glance.name: Actual Budget
      glance.icon: /assets/actual-budget.png
      glance.url: https://budget.server.netbird.cloud
      glance.description: Budgeting
      glance.id: actual-budget
      glance.category: user-facing
