services:
  server:
    image: actualbudget/actual-server:latest
    container_name: actual_server
    restart: unless-stopped
    ports:
      - "127.0.0.1:5006:5006"
    volumes:
      - /srv/docker/data/actual_budget/actual-data:/data:Z
    labels:
      glance.name: Actual Budget
      glance.icon: /assets/actual-budget.png
      glance.url: https://budget.${TAILNET_NAME}.ts.net
      glance.description: Budgeting
      glance.id: actual-budget
      glance.category: user-facing

  tailscale:
    image: tailscale/tailscale:latest
    container_name: actual-budget-ts
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-dns
    hostname: budget
    volumes:
      - tailscale_state:/var/lib/tailscale:z
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      glance.name: Tailscale
      glance.parent: actual-budget

volumes:
  tailscale_state:
